### ISSUE TITLE
A lot of details are missing?

### ISSUE THREAD

**Issue by chijames** [ozyyshr/DGM#1]
1. Where is the fix_questions.py file?
2. What is the path to all the preprocessing scripts?
3. Where is segedu/all_vocabulary.pickle?

Thanks.

**Comment by cornliu** [comment]
Hi. 
We have the same implement problems on this repo, since there are so many files/path are missing or not provided.
Could you provide more implement details? We also want to reproduce the result of this paper.
Here is my e-mail: b07901112@ntu.edu.tw.
It is really thankful if we could have further contact.
